# A list of operating systems which are used for tests
os:
  - linux
  - osx

osx_image: xcode12.2 # define OS X image which will be mounted

# Define Node.js as the programming language as we have a web application
language: node_js
node_js: '8'

addons:
  chrome: stable # Install chrome stable on operating systems

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf $HOME/.cache/electron-builder/wine; fi

# These commands are executed before the scripts are executed
install:
  # Install all dependencies listed in your package.json file
  - npm run init

script:
  - echo "Start Build"
  - ./build-mac.sh
